// ============================================================
// ADEL: Architect of Digital Armenia — Static Game Data
// ============================================================

export const AGENCIES = [
  { id: 'a01', name: 'Ministry of Finance', sensitive: false, dataClassification: 'confidential' },
  { id: 'a02', name: 'Ministry of Justice', sensitive: false, dataClassification: 'internal' },
  { id: 'a03', name: 'Ministry of Health', sensitive: false, dataClassification: 'confidential' },
  { id: 'a04', name: 'Ministry of Education', sensitive: false, dataClassification: 'internal' },
  { id: 'a05', name: 'Ministry of Labor', sensitive: false, dataClassification: 'internal' },
  { id: 'a06', name: 'Ministry of Economy', sensitive: false, dataClassification: 'internal' },
  { id: 'a07', name: 'Ministry of Transport', sensitive: false, dataClassification: 'public' },
  { id: 'a08', name: 'Ministry of Environment', sensitive: false, dataClassification: 'public' },
  { id: 'a09', name: 'Ministry of Culture', sensitive: false, dataClassification: 'public' },
  { id: 'a10', name: 'Ministry of Agriculture', sensitive: false, dataClassification: 'internal' },
  { id: 'a11', name: 'Ministry of Defense', sensitive: true, dataClassification: 'secret' },
  { id: 'a12', name: 'Ministry of Interior', sensitive: true, dataClassification: 'secret' },
  { id: 'a13', name: 'Police of Armenia', sensitive: true, dataClassification: 'secret' },
  { id: 'a14', name: 'National Security Service', sensitive: true, dataClassification: 'secret' },
  { id: 'a15', name: 'Nuclear Safety Authority', sensitive: true, dataClassification: 'secret' },
  { id: 'a16', name: 'State Revenue Committee', sensitive: false, dataClassification: 'confidential' },
  { id: 'a17', name: 'Cadastre Committee', sensitive: false, dataClassification: 'confidential' },
  { id: 'a18', name: 'Civil Aviation Authority', sensitive: false, dataClassification: 'internal' },
  { id: 'a19', name: 'State Employment Agency', sensitive: false, dataClassification: 'internal' },
  { id: 'a20', name: 'Social Insurance Fund', sensitive: false, dataClassification: 'confidential' },
  { id: 'a21', name: 'Public Services Regulatory Commission', sensitive: false, dataClassification: 'public' },
  { id: 'a22', name: 'Central Bank of Armenia', sensitive: false, dataClassification: 'confidential' },
  { id: 'a23', name: 'National Statistics Service', sensitive: false, dataClassification: 'public' },
  { id: 'a24', name: 'State Property Management Dept', sensitive: false, dataClassification: 'internal' },
  { id: 'a25', name: 'Intellectual Property Agency', sensitive: false, dataClassification: 'public' },
  { id: 'a26', name: 'Anti-Corruption Committee', sensitive: true, dataClassification: 'confidential' },
  { id: 'a27', name: 'Investigative Committee', sensitive: true, dataClassification: 'secret' },
  { id: 'a28', name: 'Prosecutor General Office', sensitive: true, dataClassification: 'secret' },
  { id: 'a29', name: 'Constitutional Court', sensitive: false, dataClassification: 'public' },
  { id: 'a30', name: 'Court of Cassation', sensitive: false, dataClassification: 'public' },
  { id: 'a31', name: 'National Assembly Secretariat', sensitive: false, dataClassification: 'internal' },
  { id: 'a32', name: "Prime Minister's Office", sensitive: false, dataClassification: 'confidential' },
  { id: 'a33', name: 'State Migration Service', sensitive: false, dataClassification: 'confidential' },
  { id: 'a34', name: 'Urban Development Committee', sensitive: false, dataClassification: 'internal' },
  { id: 'a35', name: 'Environmental Inspectorate', sensitive: false, dataClassification: 'public' },
  { id: 'a36', name: 'Food Safety Inspectorate', sensitive: false, dataClassification: 'internal' },
  { id: 'a37', name: 'Emergency Management Agency', sensitive: false, dataClassification: 'internal' },
  { id: 'a38', name: 'Tourism Committee', sensitive: false, dataClassification: 'public' },
  { id: 'a39', name: 'Youth Affairs Committee', sensitive: false, dataClassification: 'public' },
  { id: 'a40', name: 'Sports & Recreation Committee', sensitive: false, dataClassification: 'public' },
  { id: 'a41', name: 'Diaspora Affairs Office', sensitive: false, dataClassification: 'public' },
  { id: 'a42', name: 'E-Government Infrastructure Center', sensitive: false, dataClassification: 'internal' },
];

export const INFRASTRUCTURE_ZONES = [
  { id: 'cloud_a', name: 'Public Cloud A', type: 'cloud', capacity: 15, description: 'Modern cloud infrastructure — scalable, cost-effective' },
  { id: 'cloud_b', name: 'Public Cloud B', type: 'cloud', capacity: 15, description: 'Redundant cloud infrastructure — disaster recovery ready' },
  { id: 'hybrid', name: 'Hybrid Secure Zone', type: 'hybrid', capacity: 8, description: 'For sensitive agencies — private cloud + dedicated security' },
  { id: 'legacy', name: 'Legacy Server Room', type: 'legacy', capacity: 4, description: 'Existing on-premise — no migration needed but limited capability' },
];

export const DATA_FIELDS = [
  {
    id: 'df01',
    category: 'Identity',
    label: 'Personal ID Number',
    variants: ['PersonID', 'citizen_number', 'NationalID', 'ID_Number', 'pid'],
    standard: 'national_identifier',
    distractors: ['person_unique_id', 'citizen_id_code'],
  },
  {
    id: 'df02',
    category: 'Identity',
    label: 'Full Name',
    variants: ['FullName', 'citizen_name', 'NamSurname', 'full_name_arm', 'nameField'],
    standard: 'legal_full_name',
    distractors: ['citizen_full_name', 'registered_name'],
  },
  {
    id: 'df03',
    category: 'Location',
    label: 'Registered Address',
    variants: ['HomeAddress', 'reg_address', 'ResidenceAddr', 'address_reg', 'domicile'],
    standard: 'registered_domicile',
    distractors: ['home_address_official', 'legal_residence'],
  },
  {
    id: 'df04',
    category: 'Finance',
    label: 'Tax ID Number',
    variants: ['TaxID', 'tax_num', 'HVHH', 'taxpayer_code', 'fiscal_id'],
    standard: 'tax_identification_number',
    distractors: ['fiscal_taxpayer_id', 'tax_registration_num'],
  },
  {
    id: 'df05',
    category: 'Social',
    label: 'Social Security Number',
    variants: ['SocSecNum', 'ssn_am', 'social_id', 'SSN_Code', 'soc_ins_number'],
    standard: 'social_security_identifier',
    distractors: ['social_insurance_id', 'ssn_code'],
  },
  {
    id: 'df06',
    category: 'Contact',
    label: 'Mobile Phone',
    variants: ['PhoneNum', 'mobile_no', 'CellPhone', 'tel_mobile', 'phone_contact'],
    standard: 'mobile_phone_e164',
    distractors: ['mobile_number_intl', 'phone_e164'],
  },
  {
    id: 'df07',
    category: 'Contact',
    label: 'Email Address',
    variants: ['Email', 'email_addr', 'EmailContact', 'e_mail', 'contact_email'],
    standard: 'email_address_rfc5321',
    distractors: ['email_rfc_format', 'official_email'],
  },
  {
    id: 'df08',
    category: 'Business',
    label: 'Business Registration Number',
    variants: ['BizRegNum', 'company_id', 'OrgRegCode', 'reg_num_biz', 'entity_id'],
    standard: 'legal_entity_identifier',
    distractors: ['company_reg_number', 'org_legal_id'],
  },
  {
    id: 'df09',
    category: 'Finance',
    label: 'Bank Account Number',
    variants: ['BankAcct', 'account_num', 'BankIBAN', 'fin_account', 'acct_number'],
    standard: 'iban_iso13616',
    distractors: ['bank_account_iban', 'financial_account_id'],
  },
  {
    id: 'df10',
    category: 'Identity',
    label: 'Date of Birth',
    variants: ['DOB', 'birth_date', 'BirthDay', 'date_of_birth_arm', 'bdate'],
    standard: 'birth_date_iso8601',
    distractors: ['date_birth_iso', 'birthdate_standard'],
  },
];

export const ADEL_NODES = [
  { id: 'n01', name: 'Ministry of Finance', x: 150, y: 100, agencyId: 'a01' },
  { id: 'n02', name: 'Ministry of Justice', x: 350, y: 80, agencyId: 'a02' },
  { id: 'n03', name: 'Ministry of Health', x: 550, y: 100, agencyId: 'a03' },
  { id: 'n04', name: 'State Revenue Committee', x: 700, y: 200, agencyId: 'a16' },
  { id: 'n05', name: 'Social Insurance Fund', x: 650, y: 350, agencyId: 'a20' },
  { id: 'n06', name: 'State Employment Agency', x: 500, y: 430, agencyId: 'a19' },
  { id: 'n07', name: 'Ministry of Labor', x: 300, y: 430, agencyId: 'a05' },
  { id: 'n08', name: 'Cadastre Committee', x: 150, y: 350, agencyId: 'a17' },
  { id: 'n09', name: 'Ministry of Interior', x: 100, y: 220, agencyId: 'a12' },
  { id: 'n10', name: 'National Statistics Service', x: 250, y: 260, agencyId: 'a23' },
  { id: 'n11', name: 'E-Gov Infrastructure Center', x: 450, y: 260, agencyId: 'a42' },
  { id: 'hub', name: 'ADEL Hub', x: 350, y: 260, agencyId: null, isHub: true },
];

export const USEFUL_CONNECTIONS = [
  ['n01', 'hub'], ['n02', 'hub'], ['n03', 'hub'], ['n04', 'hub'],
  ['n05', 'hub'], ['n06', 'hub'], ['n07', 'hub'], ['n08', 'hub'],
  ['n09', 'hub'], ['n10', 'hub'], ['n11', 'hub'],
  ['n01', 'n04'], ['n03', 'n05'], ['n06', 'n07'],
  ['n02', 'n08'],
];

export const SERVICE_TOOLS = [
  { id: 'st01', name: 'e-Identity Gateway', category: 'Shared Service', maxAdopters: 42, requiresEid: false, requiresAdel: true, deployOrder: 1, description: 'Unified authentication for all digital services', cost: 3 },
  { id: 'st02', name: 'Digital Profile (My Data Portal)', category: 'Digital Profile', maxAdopters: 35, requiresEid: true, requiresAdel: true, minAdelConnections: 5, deployOrder: 2, description: 'Citizens access their data held by government', cost: 3 },
  { id: 'st03', name: 'No-Code Service Builder', category: 'No-Code Platform', maxAdopters: 30, requiresEid: false, requiresAdel: false, deployOrder: 1, description: 'Drag-and-drop form builder for agency services', cost: 3 },
  { id: 'st04', name: 'Notification Engine', category: 'Shared Service', maxAdopters: 40, requiresEid: false, requiresAdel: false, requiresHub: true, deployOrder: 2, description: 'Push notifications: SMS, email, in-app', cost: 3 },
  { id: 'st05', name: 'Payment Gateway', category: 'Shared Service', maxAdopters: 38, requiresEid: false, requiresAdel: false, deployOrder: 1, description: 'Unified government payment processing', cost: 3 },
  { id: 'st06', name: 'e-Signature Service', category: 'Shared Service', maxAdopters: 25, requiresEid: true, requiresAdel: false, deployOrder: 2, description: 'Legally binding digital signatures', cost: 3 },
  { id: 'st07', name: 'Analytics & BI Platform', category: 'Shared Service', maxAdopters: 20, requiresEid: false, requiresAdel: false, requiresMyData: true, deployOrder: 3, description: 'Cross-agency data analytics dashboard', cost: 3 },
  { id: 'st08', name: 'Service Registry', category: 'Shared Service', maxAdopters: 42, requiresEid: false, requiresAdel: false, deployOrder: 1, description: 'Central catalog of all government services', cost: 3 },
  { id: 'st09', name: 'Document Vault', category: 'Digital Profile', maxAdopters: 30, requiresEid: true, requiresAdel: false, deployOrder: 2, description: 'Secure digital storage for citizen documents', cost: 3 },
  { id: 'st10', name: 'Interoperability Sandbox', category: 'No-Code Platform', maxAdopters: 15, requiresEid: false, requiresAdel: true, deployOrder: 2, description: 'Testing environment for agency integrations', cost: 3 },
];

export const GOVERNMENT_SERVICES = [
  { id: 'gs01', name: 'Birth Registration', correctChannel: 'zero', hint: 'Hospital data feeds directly to Civil Registry via ADEL — no citizen action needed', requiresNotification: true, requiresEid: false },
  { id: 'gs02', name: 'Child Birth Benefit', correctChannel: 'zero', hint: 'Triggered automatically from birth registration — benefit deposited without application', requiresNotification: true, requiresEid: false },
  { id: 'gs03', name: 'Passport Renewal', correctChannel: 'portal', hint: 'Requires identity verification and physical document — portal with e-ID optimal', requiresNotification: false, requiresEid: true },
  { id: 'gs04', name: 'Tax Declaration', correctChannel: 'portal', hint: 'Complex form with document upload — web portal with e-signature is ideal', requiresNotification: false, requiresEid: true },
  { id: 'gs05', name: 'Driver License Renewal', correctChannel: 'mobile', hint: 'Frequent, routine action — mobile app with photo upload is optimal', requiresNotification: true, requiresEid: true },
  { id: 'gs06', name: 'Health Insurance Enrollment', correctChannel: 'portal', hint: 'Annual enrollment with document submission — portal workflow is most appropriate', requiresNotification: false, requiresEid: true },
  { id: 'gs07', name: 'Death Certificate', correctChannel: 'physical', hint: 'Legal requirement for in-person verification at this stage — cannot be automated yet', requiresNotification: false, requiresEid: false },
  { id: 'gs08', name: 'Business Registration', correctChannel: 'portal', hint: 'Multi-step process with legal documents — portal with e-signature is optimal', requiresNotification: false, requiresEid: true },
  { id: 'gs09', name: 'Utility Bill Payment', correctChannel: 'mobile', hint: 'Frequent small payments — mobile app is the preferred channel', requiresNotification: true, requiresEid: false },
  { id: 'gs10', name: 'Social Benefit Claim', correctChannel: 'zero', hint: 'Eligibility is computable from existing data — proactive benefit push is possible', requiresNotification: true, requiresEid: false },
  { id: 'gs11', name: 'Property Transfer', correctChannel: 'portal', hint: 'High-value transaction requiring identity verification — portal is optimal', requiresNotification: false, requiresEid: true },
  { id: 'gs12', name: 'Marriage Registration', correctChannel: 'physical', hint: 'Ceremony-based legal process — physical presence required by law', requiresNotification: false, requiresEid: false },
  { id: 'gs13', name: 'Pension Registration', correctChannel: 'zero', hint: 'Age and contribution data exists — automatic enrollment is possible', requiresNotification: true, requiresEid: false },
  { id: 'gs14', name: 'Building Permit', correctChannel: 'portal', hint: 'Complex multi-agency review — digital portal streamlines the process', requiresNotification: false, requiresEid: true },
  { id: 'gs15', name: 'Vehicle Registration', correctChannel: 'portal', hint: 'Document-heavy process — digital portal with payment integration is optimal', requiresNotification: false, requiresEid: true },
  { id: 'gs16', name: 'Education Enrollment', correctChannel: 'mobile', hint: 'Recurring annual action — mobile app is convenient for parents', requiresNotification: true, requiresEid: true },
];

export const LIFE_EVENTS = [
  {
    id: 'le01',
    name: 'Having a Baby',
    icon: '👶',
    agencies: ['a02', 'a03', 'a05', 'a20'],
    agencyNames: ['Ministry of Justice', 'Ministry of Health', 'Ministry of Labor', 'Social Insurance Fund'],
    currentSteps: 11,
    targetSteps: 1,
    currentDays: 45,
    targetDays: 0,
    description: 'Birth registration, parental leave, child benefit, health card',
    requiredConnections: [['n02', 'hub'], ['n03', 'hub'], ['n07', 'hub'], ['n05', 'hub']],
    requiredFields: ['df01', 'df02', 'df10'],
    requiredTools: ['st01', 'st04'],
    requiredChannel: 'gs01',
  },
  {
    id: 'le02',
    name: 'Getting Married',
    icon: '💍',
    agencies: ['a02', 'a05', 'a16', 'a20'],
    agencyNames: ['Ministry of Justice', 'Ministry of Labor', 'State Revenue Committee', 'Social Insurance Fund'],
    currentSteps: 8,
    targetSteps: 1,
    currentDays: 20,
    targetDays: 1,
    description: 'Marriage registration, tax status update, benefit recalculation',
    requiredConnections: [['n02', 'hub'], ['n07', 'hub'], ['n04', 'hub']],
    requiredFields: ['df01', 'df02'],
    requiredTools: ['st01'],
    requiredChannel: 'gs12',
  },
  {
    id: 'le03',
    name: 'Starting a Business',
    icon: '🏢',
    agencies: ['a02', 'a16', 'a22', 'a06'],
    agencyNames: ['Ministry of Justice', 'State Revenue Committee', 'Central Bank of Armenia', 'Ministry of Economy'],
    currentSteps: 14,
    targetSteps: 2,
    currentDays: 30,
    targetDays: 1,
    description: 'Entity registration, tax registration, bank account, permits',
    requiredConnections: [['n02', 'hub'], ['n04', 'hub'], ['n11', 'hub']],
    requiredFields: ['df04', 'df08'],
    requiredTools: ['st01', 'st05', 'st06'],
    requiredChannel: 'gs08',
  },
  {
    id: 'le04',
    name: 'Losing a Job',
    icon: '💼',
    agencies: ['a05', 'a19', 'a20', 'a16'],
    agencyNames: ['Ministry of Labor', 'State Employment Agency', 'Social Insurance Fund', 'State Revenue Committee'],
    currentSteps: 9,
    targetSteps: 1,
    currentDays: 21,
    targetDays: 0,
    description: 'Unemployment benefit registration, job seeker status, tax update',
    requiredConnections: [['n06', 'hub'], ['n07', 'hub'], ['n05', 'hub']],
    requiredFields: ['df01', 'df05'],
    requiredTools: ['st01', 'st04'],
    requiredChannel: 'gs10',
  },
  {
    id: 'le05',
    name: 'Moving to a New Address',
    icon: '🏠',
    agencies: ['a02', 'a12', 'a16', 'a05'],
    agencyNames: ['Ministry of Justice', 'Ministry of Interior', 'State Revenue Committee', 'Ministry of Labor'],
    currentSteps: 7,
    targetSteps: 1,
    currentDays: 14,
    targetDays: 1,
    description: 'Address update across all registries',
    requiredConnections: [['n02', 'hub'], ['n09', 'hub'], ['n04', 'hub']],
    requiredFields: ['df01', 'df03'],
    requiredTools: ['st01'],
    requiredChannel: 'gs03',
  },
  {
    id: 'le06',
    name: 'Retiring',
    icon: '🎯',
    agencies: ['a20', 'a16', 'a02', 'a05'],
    agencyNames: ['Social Insurance Fund', 'State Revenue Committee', 'Ministry of Justice', 'Ministry of Labor'],
    currentSteps: 10,
    targetSteps: 1,
    currentDays: 60,
    targetDays: 0,
    description: 'Pension enrollment, benefit calculation, tax status change',
    requiredConnections: [['n05', 'hub'], ['n04', 'hub'], ['n07', 'hub']],
    requiredFields: ['df01', 'df05', 'df04'],
    requiredTools: ['st01', 'st04'],
    requiredChannel: 'gs13',
  },
  {
    id: 'le07',
    name: 'Death in the Family',
    icon: '🕯️',
    agencies: ['a03', 'a02', 'a17', 'a16'],
    agencyNames: ['Ministry of Health', 'Ministry of Justice', 'Cadastre Committee', 'State Revenue Committee'],
    currentSteps: 12,
    targetSteps: 2,
    currentDays: 90,
    targetDays: 7,
    description: 'Death certificate, estate transfer, benefit termination, property transfer',
    requiredConnections: [['n03', 'hub'], ['n02', 'hub'], ['n08', 'hub'], ['n04', 'hub']],
    requiredFields: ['df01', 'df02', 'df03'],
    requiredTools: ['st01', 'st06'],
    requiredChannel: 'gs07',
  },
  {
    id: 'le08',
    name: 'Applying for a Building Permit',
    icon: '🏗️',
    agencies: ['a34', 'a35', 'a17', 'a16'],
    agencyNames: ['Urban Development Committee', 'Environmental Inspectorate', 'Cadastre Committee', 'State Revenue Committee'],
    currentSteps: 16,
    targetSteps: 3,
    currentDays: 120,
    targetDays: 14,
    description: 'Property check, environmental clearance, permit issuance, fee payment',
    requiredConnections: [['n08', 'hub'], ['n04', 'hub'], ['n11', 'hub']],
    requiredFields: ['df03', 'df08'],
    requiredTools: ['st05', 'st06'],
    requiredChannel: 'gs14',
  },
];

export const LAWS = [
  {
    id: 'law01',
    name: 'Population Register Law',
    shortName: 'Pop. Register',
    icon: '📋',
    description: 'Establishes the Population Register as the authoritative source for identity data. All agencies must use the Register as the single source of truth.',
    effect: 'Makes all aligned data fields "authoritative." Reduces duplicate records by 80. Data Layer aligned fields now show green (authoritative) instead of yellow.',
    dependentLayer: 'dataLayer',
    dependentThreshold: 50,
    impactArea: 'Data Layer',
  },
  {
    id: 'law02',
    name: 'Digital Identity Law',
    shortName: 'Digital ID',
    icon: '🪪',
    description: 'Makes e-ID legally binding for all government services. Private sector may use government e-ID for their services. Establishes liability framework for identity verification.',
    effect: 'e-ID adoption gets 2x multiplier. Unlocks private sector e-ID usage. Application Services adoption speeds up.',
    dependentLayer: 'appServices',
    dependentThreshold: 40,
    impactArea: 'Application Services',
  },
  {
    id: 'law03',
    name: 'Cybersecurity Law',
    shortName: 'Cybersecurity',
    icon: '🛡️',
    description: 'Establishes CSIRT/CERT Armenia. Mandates security standards for all government digital systems. Creates incident response protocols.',
    effect: 'Activates CSIRT/CERT (blocks threat events). Increases Trust Index by 10 points. ADEL connections get security certification.',
    dependentLayer: 'infrastructure',
    dependentThreshold: 60,
    impactArea: 'Infrastructure',
  },
  {
    id: 'law04',
    name: 'Public Information Law',
    shortName: 'Public Info',
    icon: '📢',
    description: 'Makes Data Catalog registration mandatory for all government data. Enables open data publication. Citizens have the right to know what data the government holds about them.',
    effect: 'Data Catalog registration becomes mandatory. Open data portal activated. My Data Portal citizen access enabled.',
    dependentLayer: 'dataLayer',
    dependentThreshold: 50,
    impactArea: 'Data Layer',
  },
];
